### ISSUE TITLE
1.33 is taking a lot of time was working great before the update 

### ISSUE THREAD

**Issue by davidiesel** [L1ghtmann/IAmLazy#12]
1.33 is taking a lot of time was working great before the update

**Comment by davidiesel** [comment]
14.2 12 pro max amd it used to work fine before not anymore

David Oliveira 
JMJ


On 11-Feb-2022, at 20:50, Lightmann ***@***.***> wrote:

﻿

David, what firmware, jailbreak, and device are you experiencing this on again?

Another user just reported experiencing this issue and I want to see if there are any similarities in your setups.

They're using an arm64e device on 14.8 with u0.

**Comment by L1ghtmann** [comment]
And what jailbreak?

**Comment by davidiesel** [comment]
Sorry bro Unc0ver 8.2.0

David Oliveira 
JMJ


On 11-Feb-2022, at 21:33, Lightmann ***@***.***> wrote:

﻿

And what jailbreak?

**Comment by L1ghtmann** [comment]
Fixed in v1.4.4.
