### ISSUE TITLE
Feature request for repo backups

### ISSUE THREAD

**Issue by LI0NOFGOD** [L1ghtmann/IAmLazy#18]
Feature request for iamspeed: is there a way you can add an option to backup repositories for certain package managers to ?

For example backup cydia repositories since cydia cant load all repositories 
Backup up zebra repositories (work with all repositories)
Saily is a new package manager (only works with certain repo
Sileo works with certain repositories 
Installer works with most repositories.

With the name of the package managers on the txt files along with dates it was last updated since new repos gets added to package managers all the time. And a option to select all package managers. 🙏🏽

**Comment by olivertzeng** [comment]
yes +1

**Comment by L1ghtmann** [comment]
After giving this some thought I've decided it's not likely to be implemented. Too reliant on package managers and I don't believe it can't be implemented in a clean way.
