### ISSUE TITLE
nothing backuping

### ISSUE THREAD

**Issue by skywalk1411** [L1ghtmann/IAmLazy#31]
after the progress circle finish, you get a i am lazy error, no content saved error or something, almost no time to see anything. and the export doesn't export anything, nothing in my iam folder on var/mobile/documents/... tweak does nothing now.

**Comment by L1ghtmann** [comment]
Hm, that's odd. What is your device, iOS version, iamlazy version, and jailbreak? Thanks

**Comment by L1ghtmann** [comment]
Please try v2.1.2 once it is live and let me know if you're still encountering issues. Thanks!

**Comment by skywalk1411** [comment]
> Please try v2.1.2 once it is live and let me know if you're still encountering issues. Thanks!

Iphone 12 pro max, 14.4, was the one prior 2.1.1, taurine1.1.6

It works now, but why did backup double in sizes? I do not have double the tweaks O.o Also most the time I need to start backup, it freeze, kill app, reopen, repeat a few times, and at some point, it start saving.

**Comment by L1ghtmann** [comment]
Thanks for the info! 

Did they double in size from those made with v2.1.1 or from versions earlier than that? And what step(s) does it freeze on? Thanks again!

**Comment by skywalk1411** [comment]
I am not certain, I have two here dating 2022114 and 20221020, at that time I was iamlazy uptodate, and they both 221mb, but new ones are 450mb+
