### ISSUE TITLE
Crashes when backing up

### ISSUE THREAD

**Issue by AndnixSH** [L1ghtmann/IAmLazy#32]
First time using the tweak. It crashes immediately when I try to backup. My iPad is running 14.6 with checkra1n jb

[Logs.txt](https://github.com/L1ghtmann/IAmLazy/files/10446076/Logs.txt)

**Comment by L1ghtmann** [comment]
Hey, thanks for giving IAmLazy a try! I apologize that it's not working as expected. 

Taking a look at the logs provided (thank you for those, by the way), this looks to be the same UIAlertController crash noted in #29. I've yet to complete a fix for this issue as I don't own an iPad myself and have had no one to test patched builds. 

Would you be willing to test builds that attempt to fix it? If so, please shoot me an email over at lightmanns11@gmail.com and I'll send over the latest deb. Thanks!

**Comment by AndnixSH** [comment]
Sure, I will send you an email
