### ISSUE TITLE
Request for support iOS 16.3.1

### ISSUE THREAD

**Issue by emranovin** [L1ghtmann/IAmLazy#34]
Is it possible to raise the platform support to iOS 16.3.1? So we can have this useful tool on this version as well?
p.s. how can I make the deb file by myself to test if is it working on ios 16.3.1 or not?

**Comment by L1ghtmann** [comment]
Hey! I have the version capped at 14.x.x as the jailbreaks for versions greater than that are largely rootless, which I have yet to add support for. If you are using a rootful jailbreak on iOS 16.3.1, this version cap can *likely* be removed, **at your own risk**, but your jailbreak's bootstrap repo(s) will have to be added to the filter list in [IALBackupManager.m](https://github.com/L1ghtmann/IAmLazy/blob/d9e612ea57e7cdc6d3212cf949e12756d6ab53f3/Managers/IALBackupManager.m#L165). Additionally, the method for running (un)packaging commands with setuid 0 may not work on newer versions, in which case that implementation will also have to be updated. 

I plan on adding support for rootless jailbreaks and higher versions once the iOS 15 jailbreaks are in a stable state. My only device is currently sitting on iOS 14 and I don't plan on updating it until the jailbreaks' issues have been sorted and I can trust that they won't change too drastically. Said device is capped at iOS 15.x.x, but I don't foresee that posing too many issues for adding higher versions support as IAmLazy isn't exactly version dependent. 

If you want to give packaging it a shot, you'll need [Theos](https://theos.dev/docs) and an NSTask.h header. 

Closing this in favor of #30. Thanks for your interest and support!

**Comment by emranovin** [comment]
Thanks for your effort. IAmLazy is an excellent tool indeed.
 I'm not a specialist at tweaking can you help me with the testing procedure?
 I tried to make a deb from your code. I had Theos but it gives me the NSTask error:
 `Managers/IALGeneralManager.m:13:9: fatal error: 'NSTask.h' file not found
 How should I import the NSTask package?
 
 (I tried modifying the 'control' file in the 2.1.2 deb and raising the firmware depend from 15.0 to 16.4! and after installing it with Filza doesn't give me an error but nothing appeared on the Home Screen.)
 
[  I've iPhone X at 16.3.1 with Palera1n rootfull jailbreak.]

**Comment by L1ghtmann** [comment]
You'll have to get the NSTask header from a header site such as the one available at headers.cynder.me or developer.limneos.net and place it in $THEOS/include. 

If you're not familiar with development, I would advise waiting for the official update.
