### ISSUE TITLE
Backup deb prompt error

### ISSUE THREAD

**Issue by lzq960605** [L1ghtmann/IAmLazy#35]
When backing up debs, some debs may report errors and then terminate the backup. Can we skip the error report and add an error list?
![14476F8F-C9EF-4CE0-B231-B05FFDBFFABA](https://github.com/L1ghtmann/IAmLazy/assets/52204428/b40bbccc-9f6b-4a4b-9566-7674c55ff60b)

**Comment by L1ghtmann** [comment]
This was caused by multiple things. All should be fixed in v2.3.0. Thanks again for your assistance!
