### ISSUE TITLE
The file “ai.akemi.appsyncunified.list” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by onyxcode** [L1ghtmann/IAmLazy#39]
I haven’t had AppSync installed in nearly a month.
![483D6723-219F-4522-9A9D-AA4BDC20FA77](https://github.com/L1ghtmann/IAmLazy/assets/58049576/198a7b23-51b0-4308-8d76-a489dd405304)

**Comment by L1ghtmann** [comment]
Hey, thanks for reporting this. I have a test build prepared that I believe fixes the issue. If you're willing to test it out, please shoot me an email at lightmanns11@gmail.com. Thanks!

**Comment by onyxcode** [comment]
> Hey, thanks for reporting this. I have a test build prepared that I believe fixes the issue. If you're willing to test it out, please shoot me an email at lightmanns11@gmail.com. Thanks! 

Sent that off, thanks.

**Comment by onyxcode** [comment]
I do get much farther in the process, but hit a snag at this point. 

![image](https://github.com/L1ghtmann/IAmLazy/assets/58049576/44454dea-522f-4a99-b137-bc7d99c29e0d)

**Comment by L1ghtmann** [comment]
Can you check/share the debug log located at /tmp/ial.log? Thanks!
