### ISSUE TITLE
1AmLazy Error: /var/jb/var/mobile/Documents is not writeable.

### ISSUE THREAD

**Issue by orhogi** [L1ghtmann/IAmLazy#45]
I’m unable to use it even after giving directory owner mobile and not root I’m using dopa 2.0
![B1C08981-5D9D-4993-8CF0-03A06F7F8E09](https://github.com/L1ghtmann/IAmLazy/assets/96086982/e6030839-1145-49a2-9cfe-71e74d09001c)

**Comment by orhogi** [comment]
I fixed it

**Comment by TheMachine01** [comment]
you did not, same identical issue on Iphone 14 Pro Max Dopamine IOS 16.2

**Comment by TheMachine01** [comment]
![C6096F19-5208-495F-A1F8-96E29E235752](https://github.com/user-attachments/assets/20c0fd71-49b0-4d63-a708-fdece5a652fe)

*not really identical, but hope it helps
