### ISSUE TITLE
iPhone 8 won't charge. 

### ISSUE THREAD

**Issue by dubza1111** [L1ghtmann/IAmLazy#48]
I recently tried to jail break a iPhone 8 running 16.4. unfortunately iy crashed half ways now my phone won't charge on the cable nor my computer tracks it. what do you think I should do?

**Comment by L1ghtmann** [comment]
Sorry, is this related to IAmLazy? Or are you saying during the jb process? If it's the latter, this is the wrong place to ask, sorry

**Comment by dubza1111** [comment]
no what I'm asking is will IAMLAZY help my solution?  my phone is completely dead and my computer can't detect it. I'm just asking will this app do the trick to get my phone back on so I don't waist my time.

**Comment by L1ghtmann** [comment]
IAmLazy is a *tweak* backup and restore tool. You'll likely want to charge your device and look into libimobiledevice's tooling.
