### ISSUE TITLE
Backup failed!

### ISSUE THREAD

**Issue by faithmks** [L1ghtmann/IAmLazy#49]
![2024_11_21_18_22_IMG_0378](https://github.com/user-attachments/assets/4a6d0b2e-37e5-4ae0-b8bf-203d94410f0d)
 please help me...

**Comment by L1ghtmann** [comment]
Hi, it looks like there was an issue with Canister -- the API used to obtain information on packages -- and it returned HTTP 403. Please try again when you have a moment.

**Comment by rabea98** [comment]
Hi there,

I'm experiencing the same issue and can confirm it's still ongoing. Could a fix be provided?

Thanks!

**Comment by L1ghtmann** [comment]
cc @tale

**Comment by faithmks** [comment]
Hey 2.5.0 work!
![Uploading IMG_0406.png…]()

**Comment by L1ghtmann** [comment]
@tale no worried! Appreciate the quick fix as always

**Comment by L1ghtmann** [comment]
@faithmks please reopen the issue if you are still encountering trouble

**Comment by rabea98** [comment]
@L1ghtmann issue is still present in latest version.
